# Generated by Django 5.0.1 on 2024-01-13 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriasPasteles',
            fields=[
                ('CategoriaPastelID', models.AutoField(primary_key=True, serialize=False)),
                ('NombreCategoriaPastel', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CategoriasProductos',
            fields=[
                ('CategoriaID', models.AutoField(primary_key=True, serialize=False)),
                ('NombreCategoria', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('CompraID', models.AutoField(primary_key=True, serialize=False)),
                ('FechaCompra', models.DateField()),
                ('PrecioTotal', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Reservaciones',
            fields=[
                ('ReservacionID', models.AutoField(primary_key=True, serialize=False)),
                ('FechaReservacion', models.DateField()),
                ('PrecioTotal', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('UsuarioID', models.AutoField(primary_key=True, serialize=False)),
                ('NombreUsuario', models.CharField(max_length=50)),
                ('Contraseña', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pasteles',
            fields=[
                ('PastelID', models.AutoField(primary_key=True, serialize=False)),
                ('NombrePastel', models.CharField(max_length=50)),
                ('CategoriaPastelID', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='reservaciones.categoriaspasteles')),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('ProductoID', models.AutoField(primary_key=True, serialize=False)),
                ('NombreProducto', models.CharField(max_length=50)),
                ('imagen', models.ImageField(null=True, upload_to='productos')),
                ('Precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('CategoriaID', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='reservaciones.categoriasproductos')),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('InventarioID', models.AutoField(primary_key=True, serialize=False)),
                ('CantidadDisponible', models.IntegerField()),
                ('ProductoID', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='reservaciones.productos')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('DetalleCompraID', models.AutoField(primary_key=True, serialize=False)),
                ('Cantidad', models.IntegerField()),
                ('PrecioUnitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('CompraID', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='reservaciones.compras')),
                ('ProductoID', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='reservaciones.productos')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleReservacion',
            fields=[
                ('DetalleReservacionID', models.AutoField(primary_key=True, serialize=False)),
                ('Cantidad', models.IntegerField()),
                ('PrecioUnitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ProductoID', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='reservaciones.productos')),
                ('ReservacionID', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='reservaciones.reservaciones')),
            ],
        ),
        migrations.AddField(
            model_name='reservaciones',
            name='UsuarioID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='reservaciones.usuarios'),
        ),
        migrations.AddField(
            model_name='compras',
            name='UsuarioID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='reservaciones.usuarios'),
        ),
    ]
