# Generated by Django 5.0.1 on 2024-01-13 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservaciones', '0002_remove_pasteles_categoriapastelid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservaciones',
            name='UsuarioID',
        ),
        migrations.DeleteModel(
            name='DetalleReservacion',
        ),
        migrations.DeleteModel(
            name='Reservaciones',
        ),
    ]
