# Generated by Django 5.0.1 on 2024-01-13 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservaciones', '0003_remove_reservaciones_usuarioid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallecompra',
            name='CompraID',
        ),
        migrations.AddField(
            model_name='compras',
            name='DetalleCompraID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='reservaciones.detallecompra'),
        ),
    ]
