# Generated by Django 5.0.1 on 2024-01-13 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservaciones', '0004_remove_detallecompra_compraid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='Descripcion',
            field=models.TextField(null=True),
        ),
    ]
